2018-01-04 19:41:28,297 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:41:59,721 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:52:36,886 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:53:16,433 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:55:34,496 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:56:39,765 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 19:57:40,743 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 20:03:15,697 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 20:03:26,506 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 20:06:54,779 - LogUtils.py[line:120] - ERROR: runsql exception error type "u" does not exist
LINE 1:  update fs_customer set label = array[u'\u5173\u6ce8\u533b\u...
                                              ^
 
2018-01-04 20:08:50,196 - LogUtils.py[line:120] - ERROR: runsql exception error syntax error at or near "["
LINE 1:  update fs_customer set label = [u'\u5173\u6ce8\u533b\u7597'...
                                        ^
 
2018-01-04 20:38:12,686 - LogUtils.py[line:120] - ERROR: runsql exception error malformed array literal: "{关注医疗,关注教育,}"
LINE 1:  update fs_customer set label = '{关注医疗,关注教育,}' where...
                                        ^
DETAIL:  Unexpected "}" character.
 
2018-01-04 20:38:35,045 - LogUtils.py[line:120] - ERROR: runsql exception error malformed array literal: "{关注医疗,关注教育,}"
LINE 1:  update fs_customer set label = '{关注医疗,关注教育,}' where...
                                        ^
DETAIL:  Unexpected "}" character.
 
